add docs for letsencrypt SSL cert with nginx proxy
gdg-x/hub pull request #117
Opened 2017-03-21 17:20 UTC by VikramTiwari

2017-03-21 18:15 UTC, Splaktar requested changes
Just some minor nitpicks, thank you!

2017-03-21 18:15 UTC, Splaktar commented on docs/nginx-setup.md
> +- get a cert using LetsEncrypt (Make sure LetsEncrypt is installed)
Looks really good! Can you please add a link to instructions for installing Let's Encrypt? I know that there are various different NodeJS and platform specific packages/libs.

2017-03-21 18:15 UTC, Splaktar commented on docs/nginx-setup.md
> +```
Can we split this into two blocks? One for the command one for the file contents.

2017-03-21 18:15 UTC, Splaktar commented on docs/nginx-setup.md
> +# and https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html
Can we split this into two blocks? One for the command one for the file contents.

2017-03-21 18:46 UTC, VikramTiwari commented
@Splaktar Fixed and added some more docs.

2017-03-22 18:57 UTC, Splaktar commented
Awesome, can you link to the letsencrypt doc from the nginx-setup doc please?

Once we get it merged, I'll link to the docs from the wiki.

2017-03-25 07:01 UTC, VikramTiwari commented
@Splaktar Done! They should be auto-linked internally and you will need to create a link from wiki.

2017-03-26 04:05 UTC, Splaktar approved these changes

2017-03-26 04:05 UTC, Splaktar commented
Thank you very much!

2017-03-26 04:05 UTC, merged